- name: Install proftpd
  apt:
    name=proftpd
    state=latest
  notify: Restart proftpd
  tags: l10_install_ftp_tag

- name: Create /srv/ftp dir
  file:
    path: /srv/ftp
    state: directory
    mode: 0775
    owner: root
    group: root
  tags: l10_install_ftp_tag

- copy:
    src: /home/ansible/playbook_lesson/roles/l10_install_ftp/files/ftp.msg 
    dest: /srv/ftp/ftp.msg
    owner: root
    group: root
    mode: 0644
  tags: l10_install_ftp_tag

- copy:
    src: /home/ansible/playbook_lesson/roles/l10_install_ftp/files/proftpd.conf
    dest: /etc/proftpd/proftpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags: l10_install_ftp_tag
